### ISSUE TITLE
Error en la creacion de usuario

### ISSUE THREAD

**Issue by ghost** [gh0stzk/Arch-Install#1]
Hay un error en la creacion del usuario, dice "useradd: group 'users' does not exist"

**Comment by gh0stzk** [comment]
Hola, es un bug en el mas reciente paquete de systemd https://bugs.archlinux.org/task/79619 he visto muchos post en reddit acerca de lo mismo, lo instales por archinstall o manualmente, tiene ese error.

**Comment by ghost** [comment]
Gracias por resolver mi duda 😃
